# Generated by Django 2.2.6 on 2019-11-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Timesheets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('FIRSTNAME', models.CharField(max_length=255)),
                ('LASTNAME', models.CharField(max_length=255)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('tsheets_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Timesheets.TSheetsUser')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('COMPANYNAME', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('JOBDIVANO', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('ID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('CANDIDATE', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Candidate')),
                ('JOB', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submittal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Submittal')),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('ACTIVITYID', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ACTIVITYDATE', models.DateTimeField()),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Candidate')),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Company')),
                ('JOB', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobdiva.Job')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobdiva.ParentCompany'),
        ),
    ]
