# Generated by Django 2.2.6 on 2019-10-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_code', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('unpaid_break', 'unpaid_break'), ('regular', 'regular'), ('pto', 'pto'), ('paid_break', 'paid_break')], max_length=16)),
                ('billable', models.BooleanField()),
                ('billable_rate', models.FloatField()),
                ('has_children', models.BooleanField()),
                ('assigned_to_all', models.BooleanField()),
                ('active', models.BooleanField()),
                ('last_modified', models.DateTimeField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadTimesheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSheetsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('active', models.BooleanField()),
                ('employee_number', models.IntegerField()),
                ('salaried', models.BooleanField()),
                ('exempt', models.BooleanField()),
                ('username', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('mobile_number', models.CharField(max_length=16)),
                ('last_modified', models.DateTimeField()),
                ('last_active', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('client_url', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('profile_image_url', models.URLField()),
                ('submitted_to', models.DateField()),
                ('approved_to', models.DateField()),
                ('require_password_change', models.BooleanField()),
                ('pay_rate', models.FloatField()),
                ('pay_interval', models.CharField(choices=[('hour', 'hour'), ('year', 'year')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RegularTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('tz', models.IntegerField()),
                ('tz_str', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=256)),
                ('on_the_clock', models.BooleanField()),
                ('locked', models.IntegerField()),
                ('notes', models.TextField(max_length=2048)),
                ('last_modified', models.DateTimeField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('origin_hint', models.CharField(max_length=256, null=True)),
                ('espo_processed', models.BooleanField(default=False)),
                ('jobcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Timesheets.JobCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regular_timesheet', to='Timesheets.TSheetsUser')),
            ],
        ),
        migrations.CreateModel(
            name='ManualTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('tz', models.IntegerField()),
                ('tz_str', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=256)),
                ('on_the_clock', models.BooleanField()),
                ('locked', models.IntegerField()),
                ('notes', models.TextField(max_length=2048)),
                ('last_modified', models.DateTimeField()),
                ('espo_processed', models.BooleanField(default=False)),
                ('jobcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Timesheets.JobCode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_timesheet', to='Timesheets.TSheetsUser')),
            ],
        ),
    ]
