# Generated by Django 2.2.6 on 2019-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtimesheet',
            name='espo_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='regulartimesheet',
            name='espo_processed',
            field=models.BooleanField(default=False),
        ),
    ]
