# Generated by Django 2.2.6 on 2019-10-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='man_timesheet', to='Timesheets.User'),
        ),
        migrations.AlterField(
            model_name='regulartimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regular_timesheet', to='Timesheets.User'),
        ),
    ]
