# Generated by Django 2.2.6 on 2019-10-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheets', '0002_auto_20191025_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtimesheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_timesheet', to='Timesheets.User'),
        ),
    ]
