# Generated by Django 2.2.6 on 2019-11-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheets', '0002_add_zones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TSheetsCompany',
        ),
    ]
