# Generated by Django 2.2.6 on 2019-11-17 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheets', '0003_delete_tsheetscompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadTimesheets',
        ),
    ]
